### Generate a permutration matrix

In [20]:
#The easiest way
#using shuffle function
#N dimension
import numpy as np
def perm(n):
    arr=np.eye(n,k=0)
    np.random.shuffle(arr)
    return arr
perm(10)

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
#Self writen
#Full rank with n dimension
import copy
import numpy as np
import random


def generate1(dim):
    result = []
    index = []
    for i in range(dim):
        sub = []
        for j in range(dim):
            sub.append(0)
            index.append((i, j))
        result.append(sub)
    index2 = copy.deepcopy(index)
    for i in range(dim):
        a = random.choice(index)
        result[a[0]][a[1]] = 1
        for item in index:
            if item[0] == a[0]:
                index2.remove(item)
            elif item[1] == a[1]:
                index2.remove(item)
        index = copy.deepcopy(index2)
    return np.mat(result)

In [34]:
generate1(8)

matrix([[0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0]])

In [32]:
#Self writen
#Custom different rows and columns
#May don't have mathematical meaning
import copy
import numpy as np
import random


def generate2(row, col):
    result = []
    index = []
    for i in range(row):
        sub = []
        for j in range(col):
            sub.append(0)
            index.append((i, j))
        result.append(sub)
    index2 = copy.deepcopy(index)
    for i in range(min(row, col)):
        a = random.choice(index)
        result[a[0]][a[1]] = 1
        for item in index:
            if item[0] == a[0]:
                index2.remove(item)
            elif item[1] == a[1]:
                index2.remove(item)
        index = copy.deepcopy(index2)
    return np.mat(result)

In [36]:
generate2(7, 5)

matrix([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0]])